#!/bin/bash
set -e



system_images=/home/shaojunjie/Android/Sdk/system-images

if [ ! -d $system_images ];then
	echo "错误的镜像路径：$system_images"
	exit 1
fi


#创建挂载镜像的位置
mount_path="/mnt/android_image"

if [ ! -d $mount_path ];then
	mkdir $mount_path
fi

#查找所有镜像

system_img_array=`find ${system_images} -name system.img`
host_file="${mount_path}/etc/hosts"
ip="121.41.83.91"
for img in ${system_img_array[*]}
do
	mount $img $mount_path

	echo "127.0.0.1       localhost" > $host_file 
	echo "::1             ip6-localhost" >> $host_file
	
	if [ ! -z $1 ] && [ $1 = "test" ];then
		echo "${ip} app.hxsapp.com" >> $host_file
		echo "${ip} act.hxsapp.com" >> $host_file
		echo "${ip} search.hxsapp.com" >> $host_file
		echo "${ip} bonus.hxsapp.com" >> $host_file
		echo "${ip} mall.hxsapp.com" >> $host_file
		echo "${ip} gym.hxsapp.com" >> $host_file
		echo "${ip} account.hxsapp.com" >> $host_file
		echo "${ip} base.hxsapp.com" >> $host_file
		echo "${ip} api.hxsapp.com" >> $host_file
		echo "${ip} hxsweb.hxsapp.com" >> $host_file
		echo "${ip} gymweb.hxsapp.com" >> $host_file
		echo "${ip} search.hxsapp.com" >> $host_file

	fi
	umount $mount_path
done









